"""
Kavita Amin
12/1/2017
Great Number Game: User tries to guess random number generated by the page
"""

from flask import Flask, render_template, redirect, request, session
from random import randint

app = Flask(__name__)
app.secret_key = "SecretKey"

@app.route('/')
def index(): 
    if 'randomNum' not in session: 
        session['randomNum'] = randint(1,101)
    print "random number is: ", session['randomNum']
    if 'guess' not in session: 
        session['guess'] = 0
    print "the user guessed: ", session['guess']
    return render_template("index.html")

@app.route('/process', methods=['POST'])
def process(): 
    session['guess'] = int(request.form['guess'])
    return redirect('/')

@app.route('/play_again')
def play_again(): 
    session['randomNum'] = randint(1,101)
    session['guess'] = 0
    return redirect('/')

app.run(debug=True)